<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-D54JPUJ" failures="1" tests="6" name="ChromeTest" time="166.554" errors="0" timestamp="2022-10-05T13:52:11 IST">
  <testcase classname="test.TestNg2" name="verifyMessenger" time="10.17"/>
  <testcase classname="test.TestNg2" name="verifyHelpCenter" time="4.277"/>
  <testcase classname="test.TestNg2" name="verifyHelpCenter1" time="3.938"/>
  <testcase classname="test.TestNg1" name="verifyMessenger" time="7.433"/>
  <testcase classname="test.TestNg1" name="verifyHelpCenter" time="10.294">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://www.messenger.com/hel] but found [https://www.messenger.com/help],
	expected [Messenger Help Centr] but found [Messenger Help Centre]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.messenger.com/hel] but found [https://www.messenger.com/help],
expected [Messenger Help Centr] but found [Messenger Help Centre]
at test.TestNg1.verifyHelpCenter(TestNg1.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyHelpCenter -->
  <testcase classname="test.TestNg1" name="verifyHelpCenter1" time="0.0">
    <skipped/>
  </testcase> <!-- verifyHelpCenter1 -->
</testsuite> <!-- ChromeTest -->
